### ISSUE TITLE
v2 import econnreset error

### ISSUE THREAD

**Issue by valdestron** [ojkelly/yarn.build#105]
Getting error like this while importing yarn v2

yarn plugin import https://yarn.build/v2
➤ YN0000: Downloading https://yarn.build/v2
➤ YN0001: RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/x/Projects/a/a/.yarn/releases/yarn-2.4.0.cjs:23:31294)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.e.emit (/Users/x/Projects/a/a/.yarn/releases/yarn-2.4.0.cjs:2:583004)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)

**Comment by ojkelly** [comment]
Hmm not great, but most likely an issue with Netlify or Github.

Can you download the file when you open that link? It is working for me.

That route is defined here https://github.com/ojkelly/yarn.build/blob/trunk/netlify.toml#L16

So `yarn plugin import https://github.com/ojkelly/yarn.build/releases/download/v0.9.56/plugin-build.js` will bypass Netlify if thats what's causing the issue.

**Comment by valdestron** [comment]
Works with this link
