### ISSUE TITLE
Need help - how to configure lambda to run the bundled code

### ISSUE THREAD

**Issue by ziggy6792** [ojkelly/yarn.build#140]
Sorry if this is a stupid question but how can I configure lambda to run the bundled function 

For example in your [demo](https://github.com/ojkelly/yarn.build/tree/main/e2e/lambda-project) you export your handler from [app.js](https://github.com/ojkelly/yarn.build/blob/main/e2e/lambda-project/packages/lambda/src/api.ts)

In the demo the handler is called from a separate index file with no parameters. But how do you configure lambda to call this function with the parameters the lambda received. 

This is what I tried.

1. set your `package.json > main` to `dist/app.js` 
2. `cd packages/lambda && yarn build && yarn bundle`

The resulting `entrypoint.js` in the bundle looks like this 

```
"use strict";

const path = require("path");

const pnp = require(path.normalize(path.resolve( __dirname, ".pnp.cjs"))).setup();

const index = require(path.normalize(path.resolve( __dirname,"packages/lambda/dist/app.js")));

Object.defineProperty(exports, "__esModule", { value: true });

exports.default = index;
```

3. So `entrypoint.default` is pointing to `app.js` now so I assumed the lambda entrypoint should be `bundle/entrypoint.default.handler`
![Screenshot 2021-11-11 at 12 39 10 AM](https://user-images.githubusercontent.com/60313838/141154738-4bb3526a-ba58-4dac-8df3-304d202d2b92.png)

I tried this but it didn't work. I an error
```
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Qualified path resolution failed - none of those files can be found on the disk.\n\nSource path: /var/task/bundle/packages/lambda/dist/app.js\nNot found: /var/task/bundle/packages/lambda/dist/app.js\nNot found: /var/task/bundle/packages/lambda/dist/app.js.js\nNot found: /var/task/bundle/packages/lambda/dist/app.js.json\nNot found: /var/task/bundle/packages/lambda/dist/app.js.node\n\nRequire stack:\n- /var/task/bundle/entrypoint.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
  "trace": [
    "Runtime.ImportModuleError: Error: Qualified path resolution failed - none of those files can be found on the disk.",
    "",
    "Source path: /var/task/bundle/packages/lambda/dist/app.js",
    "Not found: /var/task/bundle/packages/lambda/dist/app.js",
    "Not found: /var/task/bundle/packages/lambda/dist/app.js.js",
    "Not found: /var/task/bundle/packages/lambda/dist/app.js.json",
    "Not found: /var/task/bundle/packages/lambda/dist/app.js.node",
    "",
    "Require stack:",
    "- /var/task/bundle/entrypoint.js",
    "- /var/runtime/UserFunction.js",
    "- /var/runtime/index.js",
    "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
    "    at Module.load (internal/modules/cjs/loader.js:863:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
    "    at Function.executeUserEntryPoint (internal/modules/run_main.js:60:12)",
    "    at internal/main/run_main_module.js:17:47"
  ]
 ```
 
What am I doing wrong?

**Comment by ziggy6792** [comment]
Oh. I feel stupid.
Should be `dist/api.js` not `dist/app.js`

**Comment by ojkelly** [comment]
Glad you worked it out.

For reference the intent is that `entrypoint.js` is all you need to set as the handler.
