### ISSUE TITLE
configuration.format is deprecated and removed in latest version

### ISSUE THREAD

**Issue by oliversalzburg** [ojkelly/yarn.build#65]
**Describe the bug**
The `configuration.format` calls all no longer work in the latest yarn builds.

**To Reproduce**
1. Run `yarn build` with a yarn version built from sources `yarn set version from sources`

**Expected behavior**
`yarn build` works.

**Additional context**
```
➤ YN0001: TypeError: this.configuration.format is not a function
    at L.generateHeaderString (/tmp/stage/.yarn/plugins/@ojkelly/plugin-build.cjs:5:22464)
    at L.run (/tmp/stage/.yarn/plugins/@ojkelly/plugin-build.cjs:5:14046)
    at /tmp/stage/.yarn/plugins/@ojkelly/plugin-build.cjs:5:26168
    at async Function.start (/tmp/stage/.yarn/releases/yarn-sources.cjs:2:388418)
    at async A.execute (/tmp/stage/.yarn/plugins/@ojkelly/plugin-build.cjs:5:25214)
    at async A.validateAndExecute (/tmp/stage/.yarn/releases/yarn-sources.cjs:2:649406)
    at async Y.run (/tmp/stage/.yarn/releases/yarn-sources.cjs:17:3854)
    at async Y.runExit (/tmp/stage/.yarn/releases/yarn-sources.cjs:17:4021)
    at async u (/tmp/stage/.yarn/releases/yarn-sources.cjs:2:283982)
    at async r (/tmp/stage/.yarn/releases/yarn-sources.cjs:2:282575)
```

The calls need to be replaced with calls to `formatUtils.pretty` instead.

**Comment by oliversalzburg** [comment]
Seems #62 is fixing this :D

**Comment by arcanis** [comment]
About deprecations, note that we just merged the upgrade from Clipanion 2 to Clipanion 3, which means the commands have a slightly different syntax (cf the [doc](https://mael.dev/clipanion/docs/getting-started#your-first-command): we don't use decorators anymore).

**Comment by ojkelly** [comment]
I've tested the current latest against the latest yarn and it looks good, can anyone confirm if it's still breaking?

**Comment by oliversalzburg** [comment]
Sorry, not at the moment. Feel free to close if you checked it and no longer need the ticket :)
